import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useLiveQuery } from 'dexie-react-hooks'
import { Apple, ArrowLeft, Check, Clock3, Droplets, Footprints, Gamepad2, Phone, Pill, Timer, WifiOff } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { PatientBottomNav } from '@/components/patient/bottom-nav'
import { useAuth } from '@/lib/supabase/auth-context'
import { isSupabaseConfigured } from '@/lib/supabase/client'
import { db, type LocalReminder } from '@/lib/db/database'
import { reminderRepository } from '@/lib/repositories/reminder'

const icons = { medicine: Pill, hydration: Droplets, meal: Apple, walk: Footprints, family_call: Phone, daily_activity: Gamepad2 }
const labels = { medicine: 'Medicine', hydration: 'Hydration', meal: 'Meal', walk: 'Walk', family_call: 'Family Call', daily_activity: 'Daily Activity' }
const timeLabel = (value?: string) => value ? new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(2000, 0, 1, Number(value.split(':')[0]), Number(value.split(':')[1]))) : ''

export function RemindersPage() {
  const { user } = useAuth(); const [now, setNow] = useState(Date.now()); const [snoozeId, setSnoozeId] = useState<string | null>(null); const [optimistic, setOptimistic] = useState<Set<string>>(new Set())
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 30_000); return () => window.clearInterval(timer) }, [])
  const allReminders = useLiveQuery(() => user ? db.reminders.where('patientId').equals(user.id).and((item) => item.isActive).sortBy('scheduledTime') : [], [user?.id]) ?? []
  const allCompletions = useLiveQuery(() => user ? db.reminderCompletions.where('patientId').equals(user.id).toArray() : [], [user?.id]) ?? []
  const start = new Date(); start.setHours(0,0,0,0)
  const todayCompleted = allCompletions.filter((item) => item.completedAt >= start && (item.status === 'taken' || item.status === 'done'))
  const completedIds = useMemo(() => new Set([...todayCompleted.map((item) => item.reminderId), ...optimistic]), [todayCompleted, optimistic])
  const previouslyCompletedIds = useMemo(() => new Set(allCompletions.filter((item) => item.status === 'taken' || item.status === 'done').map((item) => item.reminderId)), [allCompletions])
  const reminders = allReminders.filter((item) => item.frequency === 'daily' || (item.frequency === 'specific_days' && item.specificDays?.includes(new Date(now).getDay())) || (item.frequency === 'once' && (!previouslyCompletedIds.has(item.id) || completedIds.has(item.id))))
  const pending = reminders.filter((item) => !completedIds.has(item.id)); const completed = reminders.filter((item) => completedIds.has(item.id))

  const complete = async (reminder: LocalReminder) => { setOptimistic((items) => new Set(items).add(reminder.id)); setSnoozeId(null); try { await reminderRepository.complete(reminder, reminder.reminderType === 'medicine' ? 'taken' : 'done'); toast.success('Reminder completed') } catch { setOptimistic((items) => { const next = new Set(items); next.delete(reminder.id); return next }); toast.error('Could not save. Please try again.') } }
  const snooze = async (reminder: LocalReminder, minutes: number) => { setSnoozeId(null); try { const until = await reminderRepository.snooze(reminder, minutes); setNow(Date.now()); toast.success(`Reminder paused until ${new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(until)}`) } catch { toast.error('Could not save. Please try again.') } }

  return <div className="patient-ui min-h-screen bg-background"><main className="mx-auto flex w-full max-w-2xl flex-col gap-8 px-5 pb-28 pt-7 sm:px-8"><Button asChild variant="ghost" className="w-fit px-3"><Link to="/patient"><ArrowLeft data-icon="inline-start" />Back</Link></Button><header><h1 className="text-[2.25rem] font-bold tracking-[-0.02em] text-foreground sm:text-[2.5rem]">My Reminders</h1><p className="mt-2 text-xl text-muted-foreground">Your caregiver prepared these reminders.</p>{(!navigator.onLine || !isSupabaseConfigured()) && <p className="mt-3 flex items-center gap-2 text-base font-medium text-muted-foreground"><WifiOff className="size-5" />Works offline</p>}</header><ReminderSection title="Today" empty="No reminders waiting right now." reminders={pending} now={now} snoozeId={snoozeId} onComplete={complete} onSnoozeOpen={setSnoozeId} onSnooze={snooze} /><ReminderSection title="Completed" empty="Completed reminders will appear here." reminders={completed} now={now} completed snoozeId={snoozeId} onComplete={complete} onSnoozeOpen={setSnoozeId} onSnooze={snooze} /></main><PatientBottomNav /></div>
}

function ReminderSection({ title, empty, reminders, now, completed, snoozeId, onComplete, onSnoozeOpen, onSnooze }: { title: string; empty: string; reminders: LocalReminder[]; now: number; completed?: boolean; snoozeId: string | null; onComplete: (item: LocalReminder) => void; onSnoozeOpen: (id: string | null) => void; onSnooze: (item: LocalReminder, minutes: number) => void }) {
  return <section aria-labelledby={`${title}-heading`} className="flex flex-col gap-4"><h2 id={`${title}-heading`} className="text-2xl font-bold text-foreground">{title}</h2>{reminders.length === 0 ? <p className="rounded-xl bg-secondary p-5 text-lg text-muted-foreground">{empty}</p> : reminders.map((item) => { const Icon = icons[item.reminderType]; const snoozed = Boolean(item.snoozedUntil && new Date(item.snoozedUntil).getTime() > now); return <article key={item.id} className={`rounded-xl border border-border bg-card p-5 ${completed ? 'opacity-75' : ''}`}><div className="flex items-center gap-4"><div className="flex size-16 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">{completed ? <Check className="reminder-check size-8" /> : <Icon className="size-8" />}</div><div className="min-w-0 flex-1"><p className="flex items-center gap-2 text-lg font-semibold text-primary"><Clock3 className="size-5" />{timeLabel(item.scheduledTime)}</p><h3 className="mt-1 text-2xl font-bold text-foreground">{item.title}</h3><p className="mt-1 text-base text-muted-foreground">{labels[item.reminderType]}</p></div></div>{snoozed ? <p role="status" className="mt-5 flex min-h-14 items-center gap-3 rounded-xl bg-secondary px-5 text-lg font-semibold text-foreground"><Timer className="size-6 text-primary" />Remind again at {new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(item.snoozedUntil!))}</p> : !completed && <><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Button size="lg" className="flex-1 text-lg" onClick={() => onComplete(item)}><Check data-icon="inline-start" />{item.reminderType === 'medicine' ? 'Taken' : 'Done'}</Button><Button size="lg" variant="outline" className="flex-1 text-lg" onClick={() => onSnoozeOpen(snoozeId === item.id ? null : item.id)}><Timer data-icon="inline-start" />Remind Me Later</Button></div>{snoozeId === item.id && <div className="mt-3 rounded-xl border border-border bg-secondary p-4"><p className="mb-3 text-lg font-semibold text-foreground">Remind me in:</p><div className="grid grid-cols-3 gap-2">{([10,30,60] as const).map((minutes) => <Button key={minutes} variant="outline" onClick={() => onSnooze(item, minutes)}>{minutes === 60 ? '1 hour' : `${minutes} min`}</Button>)}</div></div>}</>}</article> })}</section>
}
