import type { PatientTranslations } from './types'

export const as: PatientTranslations = {
  page_reader_hear: 'এই পৃষ্ঠাটো শুনক', page_reader_stop: 'পঢ়া বন্ধ কৰক', page_reader_empty: 'এই পৃষ্ঠাত পঢ়িবলৈ একো নাই।',
  voice_unavailable_device: 'এই ডিভাইচত কণ্ঠ উপলব্ধ নহয়।', voice_unavailable_assamese: 'অসমীয়া কণ্ঠ উপলব্ধ নহয়।', voice_not_configured: 'অসমীয়া কণ্ঠৰ ব্যৱস্থা কৰা হোৱা নাই।', voice_unavailable_offline: 'অফলাইনত কণ্ঠ উপলব্ধ নহয়', voice_cached_error: 'সংৰক্ষিত কণ্ঠ বজাব পৰা নগ’ল।', voice_tap_again: 'শব্দ বজাবলৈ এই পৃষ্ঠাটো শুনক বুটামটো আকৌ টেপ কৰক।', nothing_to_read: 'পঢ়িবলৈ একো নাই।', stop_voice: 'কণ্ঠ বন্ধ কৰক', stop: 'বন্ধ কৰক',
  home_new_day: 'এটি নতুন দিন', home_greeting: 'সুপ্ৰভাত, {name}', need_help: 'সহায় লাগে', start_today: 'আজিৰ কাৰ্যকলাপ আৰম্ভ কৰক', activities: 'কাৰ্যকলাপ', memory_recall: 'স্মৃতি অনুশীলন', memory_recall_desc: 'চিনাকি বস্তু মনত ৰাখক', pattern_attention: 'আৰ্হি আৰু মনোযোগ', pattern_attention_desc: 'পৰৱৰ্তীটো বিচাৰি উলিয়াওক', play: 'খেলক', feeling_today: 'আজি আপোনাৰ মন কেনেকুৱা?', daily_check_in: 'দৈনিক খবৰ', today_reminders: 'আজিৰ সোঁৱৰণী', my_memories: 'মোৰ স্মৃতিসমূহ', today_progress: 'আজিৰ অগ্ৰগতি', caregiver_view: 'যত্ন লওঁতাৰ দৃশ্য', patient_view: 'ৰোগীৰ দৃশ্য',
  app_name: 'মনৰ সাথী', select_language: 'আপোনাৰ ভাষা বাছক', select_language_label: '{language} বাছক', hear_again: 'আকৌ শুনক', home: 'মূল পৃষ্ঠা', games: 'খেলসমূহ', reminders: 'সোঁৱৰণী', memories: 'স্মৃতিসমূহ', main_navigation: 'মূল দিশনিৰ্ণয়', patient_tools: 'ৰোগীৰ সুবিধাসমূহ', back: 'পিছলৈ', next: 'পৰৱৰ্তী', loading: 'লোড হৈ আছে…', loading_activity: 'কাৰ্যকলাপ লোড হৈ আছে…', activities_label: 'কাৰ্যকলাপ',
  games_title: 'এটা কাৰ্যকলাপ বাছক', games_intro: 'লাহে লাহে কৰক। যিকোনো এটা কাৰ্যকলাপ খেলিব পাৰে।', four_gentle_activities: 'চিনাকি বস্তুৰে চাৰিটা সহজ কাৰ্যকলাপ।', six_gentle_questions: 'আৰ্হি আৰু আকৃতিৰে ছটা সহজ প্ৰশ্ন।', start_activity: 'কাৰ্যকলাপ আৰম্ভ কৰক',
  exit_title: 'কাৰ্যকলাপ এৰিব নেকি?', exit_description: 'বৰ্তমানৰ ৰাউণ্ডটো সংৰক্ষণ নহ’ব।', keep_playing: 'খেলি থাকক', leave_activity: 'কাৰ্যকলাপ এৰক',
  round_of: 'ৰাউণ্ড {current} / {total}', question_of: 'প্ৰশ্ন {current} / {total}', remember_later: 'পিছৰ বাবে এইবোৰ মনত ৰাখক', see_again_later: 'শেষৰ ফালে এই বস্তুবোৰ আকৌ দেখা পাব।', remember_order: 'ক্ৰমটো মনত ৰাখক', remember_locations: 'প্ৰতিটো বস্তুৰ ঠাই মনত ৰাখক', remember_objects: 'এই বস্তুবোৰ মনত ৰাখক', take_time: 'লাহে লাহে মন দি চাওক।', just_seen: 'এইমাত্ৰ কোনবোৰ বস্তু দেখিছিল?', seen_earlier: 'আগতে কোনবোৰ বস্তু দেখিছিল?',  memory_hint: 'বস্তুবোৰৰ কথা ভাবক আৰু সময় লওক।', hint_count: 'আপুনি {count} টা বস্তু দেখিছিল।', hint: 'ইংগিত', submit_answer: 'উত্তৰ দিয়ক', order_instruction: 'মনত ৰখা ক্ৰমত বস্তুবোৰ সজাওক', order_help: 'ক্ৰম অনুসৰি বস্তু বাছক, অথবা নম্বৰ দিয়া ঠাইলৈ টানি নিয়ক।', choose_object: 'এটা বস্তু বাছক', check_order: 'ক্ৰম পৰীক্ষা কৰক',  where_was: '{object} ক’ত আছিল?', spatial_question_count: 'প্ৰশ্ন {current} / {total}', choose_place: 'এটা ঠাই বাছক।', try_another_place: 'আন এটা ঠাই চেষ্টা কৰক।', position: 'ঠাই {number}', selected: 'নিৰ্বাচিত', good_effort: 'ভাল চেষ্টা', remembered_result: '{total} টাৰ ভিতৰত {correct} টা মনত ৰাখিলে', positions_result: '{total} টাৰ ভিতৰত {correct} টা ঠাই শুদ্ধ', found_place: 'আপুনি শুদ্ধ ঠাইটো বিচাৰি পালে', next_round: 'পৰৱৰ্তী ৰাউণ্ড', see_results: 'ফলাফল চাওক', activity_complete: 'কাৰ্যকলাপ সম্পূৰ্ণ', accuracy: 'শুদ্ধতা', objects_remembered: 'মনত ৰখা বস্তু', average_response: 'গড় উত্তৰ সময়', seconds_short: '{count} ছেকেণ্ড', count_of: '{current} / {total}', rounds_completed: 'সম্পূৰ্ণ ৰাউণ্ড', continue_pattern: 'আৰ্হি আৰু মনোযোগলৈ যাওক', back_activities: 'কাৰ্যকলাপলৈ উভতি যাওক', play_again: 'আকৌ খেলক', details_save_later: 'কাৰ্যকলাপ সম্পূৰ্ণ। কিছুমান তথ্য পিছত সংৰক্ষণ হ’ব।',
  pattern_loading: 'কাৰ্যকলাপ লোড হৈ আছে…', pattern_prompt_default: 'মন দি চাওক আৰু পৰৱৰ্তীটো বাছক।', what_comes_next: 'পৰৱৰ্তীটো কি?', which_shape_next: 'পৰৱৰ্তী আকৃতিটো কি?', which_missing: 'কোনটো বস্তু নাই?', find_different: 'বেলেগটো বিচাৰি উলিয়াওক।', look_repeats: 'কি পুনৰাবৃত্তি বা সলনি হৈছে চাওক।', look_shapes: 'প্ৰতিটো আকৃতি মন দি চাওক।', visual_sequence: 'চকুৰে দেখা ক্ৰম', answer_label: 'উত্তৰ {number}: {answer}', skip: 'এৰি যাওক', check_answer: 'উত্তৰ পৰীক্ষা কৰক', thats_okay: 'একো নহয়', thats_right: 'ঠিক হৈছে', nice_try: 'ভাল চেষ্টা', answer_is: 'উত্তৰটো হৈছে {answer}।', next_question: 'পৰৱৰ্তী প্ৰশ্ন', correct_patterns: 'শুদ্ধ আৰ্হি', questions_completed: 'সম্পূৰ্ণ প্ৰশ্ন', finish_today: 'আজিৰ কাৰ্যকলাপ শেষ কৰক', daily_complete: 'আজিৰ কাৰ্যকলাপ সম্পূৰ্ণ', daily_complete_message: 'আজি অংশ লোৱাৰ বাবে বহুত ভাল লাগিল।', return_home: 'মূল পৃষ্ঠালৈ যাওক',
  object_apple: 'আপেল', object_banana: 'কল', object_cup: 'কাপ', object_book: 'কিতাপ', object_key: 'চাবি', object_umbrella: 'ছাতি', object_clock: 'ঘড়ী', object_flower: 'ফুল', object_chair: 'চকী', object_ball: 'বল', object_spoon: 'চামুচ', object_glasses: 'চশমা', object_bag: 'বেগ', object_bottle: 'বটল', object_telephone: 'টেলিফোন',
  reminders_title: 'মোৰ সোঁৱৰণী', reminders_prepared: 'আপোনাৰ যত্ন লওঁতাই এই সোঁৱৰণীবোৰ তৈয়াৰ কৰিছে।', works_offline: 'অফলাইনতো কাম কৰে', today: 'আজি', completed: 'সম্পূৰ্ণ', no_pending_reminders: 'এতিয়া কোনো সোঁৱৰণী বাকী নাই।', no_completed_reminders: 'সম্পূৰ্ণ সোঁৱৰণী ইয়াত দেখা যাব।', medicine: 'ঔষধ', hydration: 'পানী', meal: 'আহাৰ', walk: 'খোজ কঢ়া', family_call: 'পৰিয়াললৈ ফোন', daily_activity: 'দৈনিক কাৰ্যকলাপ', taken: 'খোৱা হ’ল', done: 'হ’ল', remind_me_later: 'পিছত মনত পেলাব', remind_again_at: '{time} বজাত আকৌ মনত পেলাব', remind_in: 'কিমান সময় পিছত:', minutes: '{count} মিনিট', one_hour: '১ ঘণ্টা', reminder_saved_later: 'এই ডিভাইচত সংৰক্ষণ হ’ল। পিছত সমন্বয় হ’ব।', reminder_update_failed: 'সোঁৱৰণী সলনি কৰিব পৰা নগ’ল। আকৌ চেষ্টা কৰক।',
  memory_book: 'মোৰ স্মৃতিসমূহ', memory_book_instruction: 'আপোনাৰ আপোন মানুহ, ঠাই আৰু মুহূৰ্ত।', no_memories: 'এতিয়াও স্মৃতি নাই।', viewing_cached: 'সংৰক্ষিত স্মৃতি চাই আছে', all_memories: 'সকলো স্মৃতি', show_one: 'এটাকৈ চাওক', previous: 'আগৰটো', next_memory: 'পৰৱৰ্তীটো', memory_counter: '{current} / {total}', hear_memory: 'এই স্মৃতিটো শুনক', view_all_memories: 'সকলো স্মৃতি চাওক',
  progress_title: 'আজিৰ অগ্ৰগতি', progress_intro: 'আজি আপুনি কি সম্পূৰ্ণ কৰিলে তাৰ সহজ তালিকা।', memory_activity: 'স্মৃতি অনুশীলন', pattern_activity: 'আৰ্হি আৰু মনোযোগ', reminders_progress: 'সোঁৱৰণী {completed}/{total}', completed_mark: 'সম্পূৰ্ণ', not_yet: 'এতিয়াও নহয়', progress_complete: 'আপুনি আজিৰ কাৰ্যকলাপ সম্পূৰ্ণ কৰিলে।', progress_encouragement: 'আপুনি অংশ লোৱা প্ৰতিটো কাৰ্যকলাপেই মূল্যৱান।',
  checkin_title: 'দৈনিক খবৰ', checkin_q1: 'আজি আপোনাৰ মন কেনেকুৱা?', checkin_q2: 'আজি আপোনাৰ শক্তি কেনেকুৱা?', checkin_q3: 'আপুনি কাৰোবাৰ লগত কথা পাতিব বিচাৰে নেকি?', mood_very_good: 'খুব ভাল', mood_good: 'ভাল', mood_okay: 'ঠিকেই আছে', mood_not_good: 'ইমান ভাল নহয়', energy_good: 'ভাল', energy_okay: 'ঠিকেই আছে', energy_low: 'কম', contact_no: 'নালাগে, মই ঠিকেই আছোঁ', contact_yes: 'হয়, মোৰ যত্ন লওঁতাজনৰ সৈতে যোগাযোগ কৰক', saving: 'সংৰক্ষণ হৈ আছে…', checkin_thanks: 'খবৰ দিয়াৰ বাবে ধন্যবাদ।', saved_device: 'আপোনাৰ উত্তৰ এই ডিভাইচত সংৰক্ষণ হ’ল।', contact_caregiver: 'যত্ন লওঁতাৰ সৈতে যোগাযোগ কৰক', back_home: 'মূল পৃষ্ঠালৈ', checkin_save_error: 'আপোনাৰ উত্তৰ সংৰক্ষণ কৰিব পৰা নগ’ল। আকৌ চেষ্টা কৰক।',
  help_title: 'আমি কেনেকৈ সহায় কৰিব পাৰোঁ?', choose_option: 'তলৰ এটা বিকল্প বাছক।', call_someone: 'কাৰোবালৈ ফোন কৰক', call_caregiver: 'যত্ন লওঁতালৈ ফোন', call_family: 'পৰিয়ালৰ সদস্যলৈ ফোন', emergency_services: 'জৰুৰীকালীন সেৱা', emergency_subtitle: 'ব্যৱস্থা কৰি থোৱা জৰুৰী নম্বৰলৈ ফোন কৰক', call: 'ফোন কৰক', copy_number: 'নম্বৰ কপি কৰক', copied: 'কপি হ’ল', caregiver_call_question: 'ৰাহুলে আপোনাক ফোন কৰাটো বিচাৰে নেকি?', support_not_emergency: 'ই এটা সহায় অনুৰোধ পঠিয়ায়। ই জৰুৰীকালীন সংকেত নহয়।', ask_contact: 'যত্ন লওঁতাক মোক ফোন কৰিবলৈ কওক', request_sent: 'অনুৰোধ পঠিওৱা হ’ল', request_saved: 'আপোনাৰ অনুৰোধ সংৰক্ষণ হ’ল। সমন্বয় হ’লে ৰাহুলে জানিব।', request_saved_sync: 'আপোনাৰ অনুৰোধ সংৰক্ষণ হ’ল। এপটো সমন্বয় হ’লে ৰাহুলে দেখিব।', request_failed: 'অনুৰোধ সংৰক্ষণ কৰিব পৰা নগ’ল। আকৌ চেষ্টা কৰক।', copy_failed: 'এই নম্বৰটো কপি কৰক: {number}',
}
