// This file is auto-generated by Supabase CLI
// It matches the schema in supabase/schema.sql

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string
          role: 'patient' | 'caregiver'
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name: string
          role: 'patient' | 'caregiver'
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string
          role?: 'patient' | 'caregiver'
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      patients: {
        Row: {
          id: string
          user_id: string | null
          preferred_language: string
          date_of_birth: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          preferred_language?: string
          date_of_birth?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          preferred_language?: string
          date_of_birth?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      caregiver_patient_links: {
        Row: {
          id: string
          caregiver_id: string
          patient_id: string
          relationship: string | null
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          caregiver_id: string
          patient_id: string
          relationship?: string | null
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          caregiver_id?: string
          patient_id?: string
          relationship?: string | null
          is_primary?: boolean
          created_at?: string
        }
      }
      reminders: {
        Row: {
          id: string
          patient_id: string
          created_by: string | null
          title: string
          description: string | null
          reminder_type: 'medicine' | 'hydration' | 'activity'
          scheduled_time: string | null
          frequency: 'daily' | 'weekly' | 'as_needed'
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          created_by?: string | null
          title: string
          description?: string | null
          reminder_type: 'medicine' | 'hydration' | 'activity'
          scheduled_time?: string | null
          frequency?: 'daily' | 'weekly' | 'as_needed'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          created_by?: string | null
          title?: string
          description?: string | null
          reminder_type?: 'medicine' | 'hydration' | 'activity'
          scheduled_time?: string | null
          frequency?: 'daily' | 'weekly' | 'as_needed'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      reminder_completions: {
        Row: {
          id: string
          reminder_id: string
          patient_id: string
          status: 'taken' | 'done' | 'skipped' | 'remind_later'
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          reminder_id: string
          patient_id: string
          status: 'taken' | 'done' | 'skipped' | 'remind_later'
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          reminder_id?: string
          patient_id?: string
          status?: 'taken' | 'done' | 'skipped' | 'remind_later'
          completed_at?: string
          created_at?: string
        }
      }
      memories: {
        Row: {
          id: string
          patient_id: string
          created_by: string | null
          name: string
          relationship: string | null
          description: string | null
          image_storage_path: string | null
          image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          created_by?: string | null
          name: string
          relationship?: string | null
          description?: string | null
          image_storage_path?: string | null
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          created_by?: string | null
          name?: string
          relationship?: string | null
          description?: string | null
          image_storage_path?: string | null
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      game_sessions: {
        Row: {
          id: string
          patient_id: string
          game_type: 'memory' | 'pattern'
          difficulty_level: number
          accuracy: number
          response_time_ms: number
          hints_used: number
          score: number
          completed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          game_type: 'memory' | 'pattern'
          difficulty_level?: number
          accuracy: number
          response_time_ms: number
          hints_used?: number
          score: number
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          game_type?: 'memory' | 'pattern'
          difficulty_level?: number
          accuracy?: number
          response_time_ms?: number
          hints_used?: number
          score?: number
          completed_at?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_role: {
        Returns: string
      }
      is_caregiver_linked_to_patient: {
        Args: {
          patient_uuid: string
        }
        Returns: boolean
      }
      is_patient_owner: {
        Args: {
          patient_uuid: string
        }
        Returns: boolean
      }
      get_patient_stats: {
        Args: {
          patient_uuid: string
        }
        Returns: {
          total_sessions: number
          avg_accuracy: number
          total_reminders: number
          completed_reminders: number
          last_activity: string
        }[]
      }
      get_recent_activity: {
        Args: {
          patient_uuid: string
          limit_count?: number
        }
        Returns: {
          activity_type: string
          activity_data: Json
          created_at: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
